# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    container_name: postgreSQL
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgressql/data
volumes:
  db-data:
